spring:
  application:
    name: cgsWeb
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/cgsweb}
app:
  upload:
    path: ${IMAGE_UPLOAD_PATH:external-images/}
  images:
    base-url: ${IMAGE_BASE_URL:}
    local-url-prefix: ${IMAGE_LOCAL_URL_PREFIX:/images}
  security:
    bcrypt:
      strength: ${BCRYPT_STRENGTH:12}
  spaces:
    bucket: ${SPACES_BUCKET:cgsweb-img}
    region: ${SPACES_REGION:nyc3}
    endpoint: ${SPACES_ENDPOINT:https://nyc3.digitaloceanspaces.com}
    access-key: ${SPACES_ACCESS_KEY:}
    secret-key: ${SPACES_SECRET_KEY:}
roadie:
  url: ${ROADIE_DEV_API:https://connect-sandbox.roadie.com}
  api:
    key: ${ROADIE_API_KEY:}
    version: ${ROADIE_API_VERSION:v1}
google:
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY:}
service-area:
  origin-lat: ${SVC_AREA_LAT:38.00317456212482}
  origin-lng: ${SVC_AREA_LONG:-85.71534984109215}
  radius-miles: ${SVC_AREA_RADIUS:50}
