spring:
  application:
    name: cgsWeb
  ai:
    google:
      genai:
        projectId: ${GOOGLE_PROJECT_ID_BKP:}
        api-key: ${GOOGLE_API_KEY:}
  data:
    mongodb:
      uri: mongodb://localhost:27017/cgs_products