spring:
  application:
    name: cgsWeb
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/cgsweb}

app:
  upload:
    path: ${IMAGE_UPLOAD_PATH:external-images/}
  images:
    base-url: ${IMAGE_BASE_URL:}
    local-url-prefix: ${IMAGE_LOCAL_URL_PREFIX:/images}

  security:
    bcrypt:
      strength: ${BCRYPT_STRENGTH:12}

roadie:
  url: ${ROADIE_DEV_API:https://connect-sandbox.roadie.com}
  api:
    key: ${ROADIE_API_KEY:b5161813f1d6d54fccb187782e08d6d1014c6121}
    version: ${ROADIE_API_VERSION:v1}
